Public part2
frontend-park-mail-ru/2024_2_Komanda7 pull request #3
Opened 2024-09-29 23:53 UTC by kataamb

Большая часть изменений добавлена в эту ветку.
Также добавлен линтер (eslinter) и custom-команда для его запуска из консоли

2024-09-30 07:32 UTC, AlexandraSmirnova requested changes

2024-09-30 07:32 UTC, AlexandraSmirnova commented on eslint.config.mjs
> +  {languageOptions: { globals: globals.browser }},
тут лучше раскрыть скобки как в package.json
```
{
   languageOptions: ...
}
```

2024-09-30 07:32 UTC, AlexandraSmirnova commented on eslint.config.mjs
> +];
пустой строки не хватает. Можно добавить editorconfig и настроить, чтобы автоматически добавлять

2024-09-30 07:32 UTC, AlexandraSmirnova commented on package.json
> +  "author": "",
если поле не нужно, можно убрать его

2024-09-30 07:32 UTC, AlexandraSmirnova commented on public/components/Header/Header.js
> +      const btnLogin = document.createElement('button');
уехали отступы

2024-09-30 07:32 UTC, AlexandraSmirnova commented on public/components/Header/Header.js
> +      logoutButton.onclick = async () => {
слишком нагруженная функция получилась renderHeader. Подумайте ка декомпозировать. И логику логина лучше вынести отсюда совсем, в какой-нибудь сервис, так как это может понадобится в других частях проекта

2024-09-30 07:32 UTC, AlexandraSmirnova commented on public/components/Header/Header.js
> +          const response = await fetch('http://localhost:8080/logout', {
Такие урлы лучше выносить в константы и желательно в отдельный файл, чтобы можно было импортировать везде где нужно и изменять в случае чего только в одном месте

2024-09-30 07:32 UTC, AlexandraSmirnova commented on public/index.html
> +  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/2.3.3/purify.min.js"></script> -->
Это тут зачем? я понимаю не юзается, но закоменченный код лучше убрать

2024-09-30 07:32 UTC, AlexandraSmirnova commented on server/node_modules/cors/HISTORY.md
Это что за node_modules тут? Их в git пушить нельзя. И если вам нужны эти node_modules, то их лучше размещать на верхнем уровне проекта, на не во внутренних папках

2024-09-30 10:44 UTC, kataamb commented on public/components/Header/Header.js
> +          const response = await fetch('http://localhost:8080/logout', {
Поправим потом

2024-09-30 10:44 UTC, kataamb commented on public/components/Header/Header.js
> +      logoutButton.onclick = async () => {
Поправим позже

2024-09-30 10:44 UTC, kataamb commented on package.json
> +  "author": "",
Поправим позже

2024-10-02 10:19 UTC, AlexandraSmirnova commented on package.json
> +    "run_eslint": "find ./public -type f -name '*.js' | npx eslint"
Уже в чате писала про эту команду 
`npx eslint public/**/*.{js}`

И настроить выполнение этой команды на прекоммит (lint-staged + husky). Иначе на РК не зачтут линтер, насколько помню.

2024-10-02 10:19 UTC, AlexandraSmirnova commented on public/components/Login/Login.js
> +      const password = DOMPurify.sanitize(document.getElementById('loginPasswordEntry').value);//DOMPurify.sanitize(document.getElementById('passwordEntry').value);
Отступ выше поехал + комент лишний

2024-10-02 10:19 UTC, AlexandraSmirnova commented on public/components/Login/Login.js
> +                    if (tag === 'button') {
лишняя проверка? этот код выполнится только если tag уже button, из-за условия switch

2024-10-02 10:19 UTC, AlexandraSmirnova commented on public/components/Login/Login.js
> +            const textContent = bigObj[key]['text'];
можно не писать везде bigObj[key] (кстати можно подумать о названии, так как bigObj ни о чем не говорит)
`const { text, type, className } = bigObj[key];` И далее можно будет использовать эти переменные, это лучше чем доставать из каждый раз

2024-10-06 17:10 UTC, kataamb commented on package.json
> +  "author": "",
убрали

2024-10-06 17:11 UTC, kataamb commented on package.json
> +    "run_eslint": "find ./public -type f -name '*.js' | npx eslint"
Изменила, теперь просто *npx eslint*

2024-10-06 17:11 UTC, kataamb commented on public/components/Login/Login.js
> +      const password = DOMPurify.sanitize(document.getElementById('loginPasswordEntry').value);//DOMPurify.sanitize(document.getElementById('passwordEntry').value);
Убрали

2024-10-06 17:11 UTC, kataamb commented on public/components/Login/Login.js
> +                    if (tag === 'button') {
Лишнее убрали

2024-10-06 17:12 UTC, kataamb commented on public/components/Login/Login.js
> +            const textContent = bigObj[key]['text'];
Поправили)

2024-10-07 08:02 UTC, AlexandraSmirnova approved these changes

2024-10-07 08:39 UTC, merged